### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by epurdom** [NelleV/moanin#26]
The current data vignette seems unneeded. It is already in the documentation for the data object. 

The other vignette (installation) wouldn't be needed if we add it to Bioconductor. I would like to add it to Bioconductor because it will make a big difference in user-base and I'd be happy to help get it ready.

**Comment by NelleV** [comment]
I think the element missing right now for a bioconductor package is supporting the default API and objects typically used by bioconductor packages (summarizedExperiment?) and vignette / documentation. 
I had more specific notes from our last meeting in Berkeley about this, but I left my notebook in Grenoble.
