### ISSUE TITLE
Need to support bioconductor class

### ISSUE THREAD

**Issue by epurdom** [NelleV/moanin#49]
I've opened this discussion to talk about how to add support for taking as input for the `data` argument the standard bioconductor class, namely a `SummarizedExperiment`.

1. We could move everything over to S4. This would mean making moanin_model a S4 class, and the existing functions into S4 methods.
2. We could just have a catch inside all of our functions that would test if data inherits from a `SummarizedExperiment` class, and extract the data from there. Note that `SummarizedExperiment` can hold multiple assays, and we'd have to use the default assay. The technical reviewers might complain about this.

**Comment by epurdom** [comment]
Also, if working with `SummarizedExperiment`, could assume that the relevant meta data is saved in `colData(x)`, so can make a `moanin_model` with that information. If move to a S4 class, could actually extend the `SummarizedExperiment` class so that data and meta data are kept together in the object.

**Comment by epurdom** [comment]
Working on this on branch `EAP/moaninClass`.

**Comment by NelleV** [comment]
Can this ticket be closed? I think all the relevant code has now been merged into master.
