### ISSUE TITLE
Shouldn't have `set.seed` in function call

### ISSUE THREAD

**Issue by epurdom** [NelleV/moanin#51]
It's not generally considered good coding practice to call `set.seed` inside a function as we do in `splines_kmeans` (user is expected to set it before calling function). This gives a warning by BiocCheck

**Comment by epurdom** [comment]
However, we are calling a function from ClusterR which does just that. This may have to be something we explain to reviewers. I updated the documentation to emphasize that this an argument passed to ClusterR so clear not something we dreamed up.

**Comment by NelleV** [comment]
I don't know if it matters, but this call to `set.seed` was only done if the user passed the random seed argument to the function.

**Comment by epurdom** [comment]
I think when we submit, we are suppose to explain any NOTES remaining in `BiocCheck` and we can explain that one given that is how `ClusterR` set it up, not us.
