### ISSUE TITLE
Using use_voom_weights=TRUE with DE_timecourse gave me an error

### ISSUE THREAD

**Issue by epurdom** [NelleV/moanin#55]
I have made a vignette in moanin that runs the data on the EPICON data set. However, I am running into a few problems:

1) Using `use_voom_weights=TRUE` with `DE_timecourse` gave me an error

```
timecourseContrasts<-c("Preflowering-Control","Postflowering-Control","Postflowering-Preflowering")
splinePre<-DE_timecourse(
     data=preData[1:500,], moanin_model=moaninObject, contrasts=timecourseContrasts,
     use_voom_weights=FALSE)
```

2) I am not sure if I should be taking the log before providing the data (if using use_voom_weights=TRUE, I would think the counts are needed)?

3) kmeans clustering is not working

```
# First fit the kmeans clusters
kmeans_clusters = splines_kmeans(
    log(preData[1:500,]+1), moanin_model=moaninObject, n_clusters=3,
    random_seed=42,
    n_init=20)
```
is giving an error about including NA values. Currently I have set `eval=FALSE` to this code chunk and those that follow it.

**Comment by epurdom** [comment]
Number 3 was a divide by zero problem in `rescale_values` because there were genes with all zeros in the data I was using. I fixed the code to only divide by the max if the max is `<0`.

**Comment by NelleV** [comment]
With the current implementation, the data would need to be on the log scale: the weights are only provided as a weighting mechanism to the k-means (thus transforming the k-means into a weighted k-means), so the data is expected to be more or less gaussian.
I'll look at why the code doesn't work with weights.

**Comment by epurdom** [comment]
But the input to get the weights is counts, no? I've added logical slot to class `log_transform`, which if TRUE, gives counts to the voom, and then log transformed to the splines. However, I haven't update vignette to deal with log. I'll do that this morning.

**Comment by epurdom** [comment]
I also think that the problem with the `DE_timecourse` is that the code is

```
v = limma::voom(y, contrasts, plot=FALSE)
weights = limma::lmFit(v)
```
However, that looks odd to me for how to get the weights out, so I think there’s a mistake here. I don’t remember the limma syntax enough to be sure, but it doesn’t look like that should get the weights.
