### ISSUE TITLE
Why do we export `fit_splines`?

### ISSUE THREAD

**Issue by epurdom** [NelleV/moanin#57]
It doesn't seem to provide a user-relevant results (i.e. only coefficients), and I don't see it used in the manuscript anywhere.

**Comment by epurdom** [comment]
I've marked it `@keywords internal` for now.

**Comment by epurdom** [comment]
I removed it from being export from now to avoid complaints that we don't have examples for it.

**Comment by NelleV** [comment]
My goal was to remove anything that wasn't used in the manuscript from the public API before the submission. We can always make it public later if need be.
